// Generated by   : ImageConverter 565 Online
// Generated from : background.png
// Time generated : Thu, 10 Oct 13 14:59:20 +0200  (Server timezone: CET)
// Image Size     : 4x4 pixels
// Memory usage   : 32 bytes

#include <avr/pgmspace.h>

prog_uint16_t background[16] PROGMEM={
0x18C3, 0x0861, 0x18C3, 0x18C3, 0x18C3, 0x0861, 0x18C3, 0x0861, 0x18C3, 0x18C3, 0x18C3, 0x0861, 0x18C3, 0x0861, 0x18C3, 0x0861,   // 0x0010 (16) pixels
};
